export let msgCollection = [
	"I'm not arguing, I'm just explaining why I'm right.",
	"If at first you don't succeed, redefine success.",
	"I put the 'elusive' in 'selfie'.",
	"I'm on a seafood diet. I see food and I eat it.",
	"I used to play piano by ear, but now I use my hands.",
	"I'm not clumsy, I'm just dancing with the floor.",
	"I'm not saying I'm Wonder Woman, I'm just saying no one has ever seen me and Wonder Woman in the same room.",
	"I told my wife she was drawing her eyebrows too high. She seemed surprised.",
	"If you think nobody cares if you're alive, try missing a couple of payments.",
	"Life is short. Smile while you still have teeth.",
	"I'm not lazy, I'm on energy-saving mode.",
	"I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
	"I only know 25 letters of the alphabet. I don't know y.",
	"I'd like to help you out. Which way did you come in?",
	"I don't need anger management. You just need to stop making me angry!",
	"I'm not arguing, I'm simply explaining why I'm right.",
	"I'm not shy, I'm just good at figuring out who's worth talking to.",
	"I'm not late, everyone else is just early.",
	"I don't go crazy. I am crazy. I just go normal from time to time.",
	"I'm not a complete idiot; some parts are missing.",
	"I'm not saying you're stupid, I'm just saying you have bad luck thinking.",
	"I'm not a player, I'm the game.",
	"I'm not short, I'm concentrated awesome.",
	"I'm not short, I'm fun-sized.",
	"I'm not short, I'm vertically efficient.",
	"I'm not short, I'm a people McNugget.",
	"I'm not short, I'm travel-size for your convenience.",
	"I'm not a morning person. I'm not an afternoon person. I'm barely even a person.",
	"I'm not fat. I'm just so sexy it overflows.",
	"I'm not fat. It's just that my awesomeness is too big to be contained in a smaller body.",
	"I'm not fat. It's just my body has a high storage capacity.",
	"I'm not fat. I'm just so darn attractive that it's hard to keep my body in proportion.",
	"I'm not arguing, I'm just explaining why I'm right. Again.",
	"I'm not old. I'm chronologically gifted.",
	"I'm not a baker, but I have a lot of dough.",
	"I'm not an early bird or a night owl. I'm some form of permanently exhausted pigeon.",
	"I'm not short. I'm concentrated awesome.",
	"I'm not saying I'm Batman. I'm just saying no one has ever seen me and Batman in the same room.",
	"I'm not saying I'm Wonder Woman, I'm just saying no one has ever seen me and Wonder Woman in the same room.",
	"I'm not saying you're stupid, but you have bad luck thinking.",
	"I'm not shy, I'm just good at figuring out who's worth talking to.",
	"I'm not sure how many problems I have because math is one of them.",
	"I'm not saying you're old, but if you were a vegetable, you'd be a 'historical' one.",
	"I'm not a doctor, but I play one on the internet.",
	"I'm not fat, I'm just easy to see.",
	"I'm not lazy, I'm just highly motivated to do nothing.",
	"I'm not perfect, but at least I'm not you.",
	"I'm not short, I'm concentrated awesome.",
	"I'm not small, I'm space-efficient.",
	"I'm not superstitious. I'm just a little stitious.",
	"I'm not weird. I'm limited edition.",
	"I'm not yelling, I'm just very enthusiastic.",
	"I'm only responsible for what I say, not for what you understand.",
	"I'm outdoorsy in that I like getting drunk on patios.",
	"I'm really good at stuff until people watch me do that stuff.",
	"I'm silently correcting your grammar in my head.",
	"I'm so cool that even ice cubes are jealous.",
	"I'm so old, I remember when emojis were called 'hieroglyphics'.",
	"I'm so poor that I can't even pay attention.",
	"I'm so sweet, I've given myself diabetes.",
	"I'm the kind of person your parents warned you about.",
	"I'm trying to kick caffeine, but I'm having a tea-rrible time.",
	"I'm writing a book. I've got the page numbers done.",
	"I've been dieting for months, and I've only lost one minute off my life expectancy.",
	"I've finally found the recipe for success: Just stay in bed.",
	"I've had amnesia for as long as I can remember.",
	"I've stopped drinking for good. Now I only drink for evil.",
	"I've tried to stop swearing, but I cunt.",
	"I've used up all my sick days, so I'm calling in dead.",
	"I've worked really hard to get to where I am today. But I haven't worked hard to get to where you are today.",
	"If a jogger runs at the speed of sound, can he still hear his iPod?",
	"If at first you don't succeed, skydiving is not for you.",
	"If at first you don't succeed, maybe skydiving isn't your thing.",
	"If Cinderella's shoe fit perfectly, why did it fall off in the first place?",
	"If I'm not back in five minutes... wait longer!",
	"If I've learned anything from video games, it's that when you meet enemies, you're going the right way.",
	"If I'm not on time, I'm early.",
	"If it's called tourist season, why can't we shoot them?",
	"If life gives you lemons, just add vodka.",
	"If nothing goes right, go left.",
	"If people say they just love the smell of books, I always want to pull them aside and ask, 'To be clear, do you know how reading works?'",
	"If procrastination was an Olympic sport, I'd compete in it later.",
	"If there's a will, I want to be in it.",
	"If there's no such thing as a stupid question, then what kind of questions do stupid people ask? Do they get smart just in time to ask questions?",
	"If we're not meant to have midnight snacks, why is there a light in the fridge?",
	"If you can't convince them, confuse them.",
	"If you can't remember my name, just call me tomorrow.",
	"If you don't like my sense of humor, please tell me. I have several.",
	"If you find it hard to laugh at yourself, I would be happy to do it for you.",
	"If you keep your feet firmly on the ground, you'll have trouble putting on your pants.",
	"If you think nobody cares about you, try missing a couple of payments.",
	"If you think nobody cares if you're alive, try missing a couple of car payments.",
	"If you think nobody cares, try missing a couple of payments.",
	"If you want to know if someone is stupid, ask them if they believe in stereotypes.",
	"If you're going to do something tonight that you'll be sorry for tomorrow morning, sleep late.",
	"If you're not supposed to eat at night, why is there a light bulb in the refrigerator?",
	"If you're not willing to risk it all, you don't want it bad enough – pizza, that is.",
	"If you're waiting for me to care, I hope you brought something to eat, 'cause it's gonna be a while.",
	"I'll admit I have a perfect body. But it's in the trunk and it's starting to smell.",
	"I'll believe in reincarnation in my next life.",
];


